### ISSUE TITLE
Cannot read property '_statcode' of undefined

### ISSUE THREAD

**Issue by Conmmander** [maxrumsey/hookcord#11]
I decided to use this, and received an error.

"(node:19916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_statcode' of undefined
    at Hook.fire (C:\Users\...\Desktop\dudes bot\node_modules\hookcord\src\hook.js:71:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:19916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

What is going on here?

**Comment by maxrumsey** [comment]
Hey, sorry for the late response. I will have a look for you!

**Comment by Conmmander** [comment]
Much appreciated!

**Comment by ghost** [comment]
I'm experiencing the same error when I run the code from your Medium post @maxrumsey

**Comment by true-zero** [comment]
@maxrumsey I've resolved this issue.
